org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=D:/intelliJSSL/jssecacerts -Djavax.net.ssl.trustStorePassword=changeit
org.gradle.java.home=D:/jsProject/zulu21
org.gradle.java.installations.paths=D:/jsProject/zulu21
org.gradle.configuration-cache=true
org.gradle.caching=true
